spring.application.name=kamil-auth-service
server.port=8081

# Virtual Threads
spring.threads.virtual.enabled=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-muddy-smoke-airjno2p-pooler.c-4.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_K5Uq2bpYSyaQ
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m


jwt.secret=8f9d2a7c6b5e4f3d2a1b9c8e7d6f5a4c
jwt.access-token-expiration=900